package com.pantrymanager.presentation.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.pantrymanager.domain.entity.Category
import com.pantrymanager.domain.usecase.category.AddCategoryUseCase
import com.pantrymanager.domain.usecase.category.GetAllCategoriesUseCase
import com.pantrymanager.domain.usecase.category.UpdateCategoryUseCase
import com.pantrymanager.domain.usecase.category.DeleteCategoryUseCase
import com.pantrymanager.domain.usecase.category.GetCategoryByIdUseCase
import com.pantrymanager.domain.usecase.category.PopulateCategoriesFromOpenAIUseCase
import com.pantrymanager.domain.usecase.category.RemoveDuplicateCategoriesUseCase
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

data class CategoryState(
    val name: String = "",
    val categories: List<Category> = emptyList(),
    val selectedCategories: Set<Long> = emptySet(),
    val isSelectionMode: Boolean = false,
    val isLoading: Boolean = false,
    val errorMessage: String? = null,
    val isSuccess: Boolean = false,
    val nameError: String? = null,
    val editingCategory: Category? = null,
    val showEditDialog: Boolean = false,
    val showDeleteDialog: Boolean = false,
    val categoryToDelete: Category? = null,
    val showMultiDeleteDialog: Boolean = false
)

@HiltViewModel
class CategoryViewModel @Inject constructor(
    private val addCategoryUseCase: AddCategoryUseCase,
    private val getAllCategoriesUseCase: GetAllCategoriesUseCase,
    private val updateCategoryUseCase: UpdateCategoryUseCase,
    private val deleteCategoryUseCase: DeleteCategoryUseCase,
    private val getCategoryByIdUseCase: GetCategoryByIdUseCase,
    private val populateCategoriesFromOpenAIUseCase: PopulateCategoriesFromOpenAIUseCase,
    private val removeDuplicateCategoriesUseCase: RemoveDuplicateCategoriesUseCase
) : ViewModel() {

    private val _state = MutableStateFlow(CategoryState())
    val state: StateFlow<CategoryState> = _state.asStateFlow()

    init {
        loadCategories()
    }

    fun onNameChanged(name: String) {
        _state.value = _state.value.copy(
            name = name,
            nameError = null
        )
    }

    fun addCategory() {
        if (!validateCategory()) return

        viewModelScope.launch {
            _state.value = _state.value.copy(isLoading = true, errorMessage = null)
            
            try {
                /*
                // Código de conexão com banco comentado
                val category = Category(
                    id = 0, // Will be auto-generated by Room
                    name = _state.value.name.trim()
                )
                
                addCategoryUseCase(category)
                loadCategories() // Reload the list
                */
                
                // Simulação de delay para mostrar loading
                kotlinx.coroutines.delay(1000)
                
                _state.value = _state.value.copy(
                    isLoading = false,
                    isSuccess = true,
                    name = "", // Clear the form
                    errorMessage = "Categoria cadastrada com sucesso!"
                )
            } catch (e: Exception) {
                _state.value = _state.value.copy(
                    isLoading = false,
                    errorMessage = e.message ?: "Erro desconhecido"
                )
            }
        }
    }

    fun startEditCategory(category: Category) {
        _state.value = _state.value.copy(
            editingCategory = category,
            name = category.name,
            showEditDialog = true,
            nameError = null
        )
    }

    fun updateCategory() {
        val editingCategory = _state.value.editingCategory ?: return
        if (!validateCategory(editingCategory.id)) return

        viewModelScope.launch {
            _state.value = _state.value.copy(isLoading = true, errorMessage = null)
            
            try {
                /*
                // Código de conexão com banco comentado
                val updatedCategory = editingCategory.copy(
                    name = _state.value.name.trim()
                )
                
                updateCategoryUseCase(updatedCategory)
                loadCategories()
                */
                
                // Simulação de delay para mostrar loading
                kotlinx.coroutines.delay(1000)
                
                _state.value = _state.value.copy(
                    isLoading = false,
                    isSuccess = true,
                    showEditDialog = false,
                    editingCategory = null,
                    name = "",
                    errorMessage = "Categoria atualizada com sucesso!"
                )
            } catch (e: Exception) {
                _state.value = _state.value.copy(
                    isLoading = false,
                    errorMessage = e.message ?: "Erro desconhecido"
                )
            }
        }
    }

    fun confirmDeleteCategory(category: Category) {
        _state.value = _state.value.copy(
            categoryToDelete = category,
            showDeleteDialog = true
        )
    }

    fun deleteCategory() {
        val categoryToDelete = _state.value.categoryToDelete ?: return

        viewModelScope.launch {
            _state.value = _state.value.copy(isLoading = true, errorMessage = null)
            
            try {
                /*
                // Código de conexão com banco comentado
                deleteCategoryUseCase(categoryToDelete)
                loadCategories()
                */
                
                // Simulação de delay para mostrar loading
                kotlinx.coroutines.delay(1000)
                
                _state.value = _state.value.copy(
                    isLoading = false,
                    isSuccess = true,
                    showDeleteDialog = false,
                    categoryToDelete = null,
                    errorMessage = "Categoria deletada com sucesso!"
                )
            } catch (e: Exception) {
                _state.value = _state.value.copy(
                    isLoading = false,
                    errorMessage = e.message ?: "Erro ao excluir categoria"
                )
            }
        }
    }

    fun cancelEdit() {
        _state.value = _state.value.copy(
            showEditDialog = false,
            editingCategory = null,
            name = "",
            nameError = null
        )
    }

    fun cancelDelete() {
        _state.value = _state.value.copy(
            showDeleteDialog = false,
            categoryToDelete = null
        )
    }

    fun clearSuccess() {
        _state.value = _state.value.copy(isSuccess = false)
    }

    fun clearError() {
        _state.value = _state.value.copy(errorMessage = null)
    }

    fun toggleCategorySelection(categoryId: Long) {
        val currentSelection = _state.value.selectedCategories
        val newSelection = if (currentSelection.contains(categoryId)) {
            currentSelection - categoryId
        } else {
            currentSelection + categoryId
        }
        
        _state.value = _state.value.copy(
            selectedCategories = newSelection,
            isSelectionMode = newSelection.isNotEmpty()
        )
    }

    fun selectAllCategories() {
        // Include both default categories and saved categories
        val allCategories = com.pantrymanager.data.defaults.DefaultCategories.defaultCategories + _state.value.categories
        _state.value = _state.value.copy(
            selectedCategories = allCategories.map { it.id }.toSet(),
            isSelectionMode = true
        )
    }

    fun clearSelection() {
        _state.value = _state.value.copy(
            selectedCategories = emptySet(),
            isSelectionMode = false
        )
    }

    fun confirmMultipleDelete() {
        _state.value = _state.value.copy(showMultiDeleteDialog = true)
    }

    fun cancelMultipleDelete() {
        _state.value = _state.value.copy(showMultiDeleteDialog = false)
    }

    fun deleteSelectedCategories() {
        val selectedIds = _state.value.selectedCategories
        if (selectedIds.isEmpty()) return

        // Only allow deletion of user-created categories (not default ones)
        // Default categories have negative IDs, user categories have positive IDs
        val userCategoryIds = selectedIds.filter { id -> 
            _state.value.categories.any { it.id == id }
        }
        
        if (userCategoryIds.isEmpty()) {
            _state.value = _state.value.copy(
                errorMessage = "Não é possível excluir categorias padrão do sistema",
                showMultiDeleteDialog = false
            )
            return
        }

        viewModelScope.launch {
            _state.value = _state.value.copy(isLoading = true, errorMessage = null)
            
            try {
                /*
                // Código de conexão com banco comentado
                userCategoryIds.forEach { categoryId ->
                    deleteCategoryUseCase(categoryId)
                }
                loadCategories()
                */
                
                // Simulação de delay para mostrar loading
                kotlinx.coroutines.delay(1500)
                
                _state.value = _state.value.copy(
                    isLoading = false,
                    isSuccess = true,
                    selectedCategories = emptySet(),
                    isSelectionMode = false,
                    showMultiDeleteDialog = false,
                    errorMessage = "${userCategoryIds.size} categoria(s) excluída(s) com sucesso!"
                )
            } catch (e: Exception) {
                _state.value = _state.value.copy(
                    isLoading = false,
                    errorMessage = e.message ?: "Erro ao excluir categorias"
                )
            }
        }
    }

    private fun validateCategory(excludeId: Long = -1): Boolean {
        val trimmedName = _state.value.name.trim()
        
        if (trimmedName.isBlank()) {
            _state.value = _state.value.copy(nameError = "Nome da categoria é obrigatório")
            return false
        }

        // Check if category already exists (excluding current category when editing)
        val categoryExists = _state.value.categories.any { 
            it.name.equals(trimmedName, ignoreCase = true) && it.id != excludeId
        }
        
        if (categoryExists) {
            _state.value = _state.value.copy(nameError = "Esta categoria já existe")
            return false
        }

        return true
    }

    private fun loadCategories() {
        viewModelScope.launch {
            try {
                // Carregar categorias do banco de dados
                val categories = getAllCategoriesUseCase()
                _state.value = _state.value.copy(categories = categories)
            } catch (e: Exception) {
                // Se houver erro no banco, mostrar pelo menos as categorias padrão
                _state.value = _state.value.copy(
                    categories = emptyList(), // Lista das categorias personalizadas será vazia
                    errorMessage = "Erro ao carregar categorias personalizadas: ${e.message}"
                )
            }
        }
    }
    
    /**
     * Busca categorias automaticamente via ChatGPT e cadastra as novas
     */
    fun populateCategoriesFromChatGPT() {
        viewModelScope.launch {
            _state.value = _state.value.copy(isLoading = true, errorMessage = null)
            
            try {
                val result = populateCategoriesFromOpenAIUseCase()
                
                if (result.isSuccess) {
                    val addedCount = result.getOrThrow()
                    loadCategories() // Recarregar lista
                    _state.value = _state.value.copy(
                        isLoading = false,
                        errorMessage = "✅ $addedCount novas categorias encontradas e cadastradas via ChatGPT!"
                    )
                } else {
                    _state.value = _state.value.copy(
                        isLoading = false,
                        errorMessage = "Erro ao buscar categorias no ChatGPT: ${result.exceptionOrNull()?.message}"
                    )
                }
            } catch (e: Exception) {
                _state.value = _state.value.copy(
                    isLoading = false,
                    errorMessage = "Erro ao buscar categorias: ${e.message}"
                )
            }
        }
    }
    
    /**
     * Remove categorias duplicadas
     */
    fun removeDuplicateCategories() {
        viewModelScope.launch {
            _state.value = _state.value.copy(isLoading = true, errorMessage = null)
            
            try {
                val result = removeDuplicateCategoriesUseCase()
                
                if (result.isSuccess) {
                    val removedCount = result.getOrThrow()
                    loadCategories() // Recarregar lista
                    _state.value = _state.value.copy(
                        isLoading = false,
                        errorMessage = if (removedCount > 0) "🗑️ $removedCount categorias duplicadas removidas!" 
                                     else "Nenhuma categoria duplicada encontrada."
                    )
                } else {
                    _state.value = _state.value.copy(
                        isLoading = false,
                        errorMessage = "Erro ao remover duplicatas: ${result.exceptionOrNull()?.message}"
                    )
                }
            } catch (e: Exception) {
                _state.value = _state.value.copy(
                    isLoading = false,
                    errorMessage = "Erro ao remover duplicatas: ${e.message}"
                )
            }
        }
    }
}
